### ISSUE TITLE
Create database structure for sessions

### ISSUE THREAD

**Issue by AtriLahiji** [SyncED-org/Pollo#5]

**Comment by AtriLahiji** [comment]
@IxLahiji This one is a bit weird. Trying to think of how to lay out this database. We should probably have a chit chat about how this is gonna work

**Comment by AtriLahiji** [comment]
I have a template up on the firebase console. Might need some reviewing.

**Comment by AtriLahiji** [comment]
Plan thus far:

- Split database into collections for sessions, active sessions, questions, and responses
- Use 4 character alphanumeric codes
- Have scheduled tasks run every day to recycle active session codes

**Comment by IxLahiji** [comment]
We will be using the realtime database, which has inherent tracking of active sessions.
